name: Develop Github Actions

on:
  push:
    branches:
    - main
    - test
  pull_request:
    branches:
    - main

  # Allow manual
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello Action
      - name: Run a multiline script
        run: |
          whoami
          env
